rvm:
  - 1.9.3
gemfile:
  - gemfiles/rails-3-2-stable.gemfile
  - gemfiles/rails-4-0-stable.gemfile
  - gemfiles/rails-4-1-stable.gemfile
  - gemfiles/rails-4-2-stable.gemfile
matrix:
  include:
    - rvm: 2.2.1
      gemfile: gemfiles/rails-master.gemfile
before_script:
  - 'sh -e /etc/init.d/xvfb start'
-env:
  - DISPLAY=':99.0'
script: bundle exec rake --trace